# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick Roberts | Front End Developer
email: admin@patrickroberts.io
description: > # this means to ignore newlines until "baseurl:"
  I am a Frontend developer looking to start my career with a great team in Canberra. I have experience building with Sass, HTML5, jQuery, Jekyll, GitHub and to WCAG AA standards. I am enthusiastic, hard working, and ready to learn and build my skills. If I sound like the right person for your company, please get in touch. I'd love to talk to you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://patrickroberts.io" # the base hostname & protocol for your site
twitter_username: proberts93
github_username:  patrickroberts93

sass:
  style: compressed
  
# Build settings
markdown: kramdown
